<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="in-madhurvk-1" name="scripts.TestValidLogin" tests="2" failures="1" timestamp="17 Nov 2019 06:41:08 GMT" time="22.347" errors="1">
  <testcase name="endReport" time="9.428" classname="scripts.TestValidLogin">
    <error type="org.apache.commons.mail.EmailException" message="Sending the email to the following server failed : na-mailrelay-t3.na.uis.unisys.com:25">
      <![CDATA[org.apache.commons.mail.EmailException: Sending the email to the following server failed : na-mailrelay-t3.na.uis.unisys.com:25
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469)
	at org.apache.commons.mail.Email.send(Email.java:1496)
	at generics.EmailsUtils.sendEmailReport(EmailsUtils.java:54)
	at generics.BaseTest.endReport(BaseTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.TestRunner.afterRun(TestRunner.java:958)
	at org.testng.TestRunner.run(TestRunner.java:606)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: na-mailrelay-t3.na.uis.unisys.com, 25; timeout 60000;
  nested exception is:
	java.net.UnknownHostException: na-mailrelay-t3.na.uis.unisys.com
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2053)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:697)
	at javax.mail.Service.connect(Service.java:364)
	at javax.mail.Service.connect(Service.java:245)
	at javax.mail.Service.connect(Service.java:194)
	at javax.mail.Transport.send0(Transport.java:253)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459)
	... 29 more
Caused by: java.net.UnknownHostException: na-mailrelay-t3.na.uis.unisys.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:310)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:236)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2019)
	... 36 more
]]>
    </error>
  </testcase> <!-- endReport -->
  <testcase name="validLogin" time="12.919" classname="scripts.TestValidLogin">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://inteliserve.unisys] but found [https://inteliserve.unisys.com/demo/dashboard#access_token=eyJraWQiOiIwamR1RkJHTXZsbEdHUHBHd0NqdlB0cldhdXlIWk96TjJiSGNiT3lxbktjPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIxNzUwYzE3My1lZjBhLTQ1ZTAtOWJkYy0wZDVkZDA2YWUzODYiLCJjb2duaXRvOmdyb3VwcyI6WyJ1cy1lYXN0LTFfQUd5ME8xRHFvX0ludGVsaUFwcEdyeW1hdHRlckF1dGgwIl0sInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXV0aF90aW1lIjoxNTUwNzYyMDA0LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9BR3kwTzFEcW8iLCJleHAiOjE1NTA3NjU2MDQsImlhdCI6MTU1MDc2MjAwNCwidmVyc2lvbiI6MiwianRpIjoiZjgzODk2NDctMjNjOC00YTJjLTk4OWItMDVjZDUwNmRiYjg4IiwiY2xpZW50X2lkIjoiM2FqOG1qMGptZDk5MHU1M2ViaTU3Y3Q4bjgiLCJ1c2VybmFtZSI6IkludGVsaUFwcEdyeW1hdHRlckF1dGgwX2F1dGgwfDViYzczOWZkYzA3YTM1N2FlN2VjNGUzNCJ9.a6ZXpRVq1t8xQHNhgJc1tXPMXQwljJSo9nylGa-f8hbPuo2ake0tXm6bfwG1fjzzIz2nYxZAznW4C5-YanGSUR87YcwyuMXb-XwK0VnS1RJHf5pNnXnJJx70S5KLJ7ScrBHyDPqXsHZmDtxV9oGar-VBBsoHqoJ0Kn1nQI0Pn7VIsHd_iaTgDOoufQFhXKklCYZZoDc_i8homkjnnuMkUAB16sYvytlgXldjeNGhqQn_mE-BDlQgiT9hOy1leyHF5IIOvYOSTEGO6Yrmkk-XcZlo0J6pvXc82ONPFq4fjt41kmsaB2MPEDwx8DXNZqi23I-pFX7OUm7ZU1Uh55d0mg&amp;id_token=eyJraWQiOiJ1RTVxbVwvdk5PemtyWjFKWFBYSXkzY3hwaE00M25rNjBvV1Vsb0I3emt0RT0iLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiSVFpam5SZU9rLTFFNlY1d3h6cEt6ZyIsInN1YiI6IjE3NTBjMTczLWVmMGEtNDVlMC05YmRjLTBkNWRkMDZhZTM4NiIsImNvZ25pdG86Z3JvdXBzIjpbInVzLWVhc3QtMV9BR3kwTzFEcW9fSW50ZWxpQXBwR3J5bWF0dGVyQXV0aDAiXSwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9BR3kwTzFEcW8iLCJjb2duaXRvOnVzZXJuYW1lIjoiSW50ZWxpQXBwR3J5bWF0dGVyQXV0aDBfYXV0aDB8NWJjNzM5ZmRjMDdhMzU3YWU3ZWM0ZTM0IiwiYXVkIjoiM2FqOG1qMGptZDk5MHU1M2ViaTU3Y3Q4bjgiLCJpZGVudGl0aWVzIjpbeyJ1c2VySWQiOiJhdXRoMHw1YmM3MzlmZGMwN2EzNTdhZTdlYzRlMzQiLCJwcm92aWRlck5hbWUiOiJJbnRlbGlBcHBHcnltYXR0ZXJBdXRoMCIsInByb3ZpZGVyVHlwZSI6IlNBTUwiLCJpc3N1ZXIiOiJ1cm46aW50ZWxsaWFwcC5hdXRoMC5jb20iLCJwcmltYXJ5IjoidHJ1ZSIsImRhdGVDcmVhdGVkIjoiMTU0MDM0NjEzOTE1NCJ9XSwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE1NTA3NjIwMDQsImV4cCI6MTU1MDc2NTYwNCwiaWF0IjoxNTUwNzYyMDA0LCJlbWFpbCI6InJ5YW5AZ3J5bWF0dGVyLmNvbSJ9.ZZ1k6n9siToc6ZpbZRG6F0EFK5UzJ68RCTYN1LAGGlYiO54rIdZcoGmaGRPdFVLMy0RnBgOsEKxv8-W7e1heoJj3GHJezXpney80GhxVhpFvu2HjXMNJpzrHBefKJMrjX5EjErFIH8ERGhCM87cupf9MYJSAo0jc3Rnf81R0nAsbvNI4uoyKp_USMKldliDPdRINR74PcJnp04e_Jk4gZ-lVi_xIYHdqBG5WtaexD-IvD5hizNMteywyLKTUTAc5nnTLZOtiAQqwveePIWcF6keJxpMo59p8_liQc5gB4y-vog61U-KRraNQguHIAbUh8Nk-ViPxeAtR2p9Ywt5RtA&amp;token_type=Bearer&amp;expires_in=3600]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [https://inteliserve.unisys] but found [https://inteliserve.unisys.com/demo/dashboard#access_token=eyJraWQiOiIwamR1RkJHTXZsbEdHUHBHd0NqdlB0cldhdXlIWk96TjJiSGNiT3lxbktjPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIxNzUwYzE3My1lZjBhLTQ1ZTAtOWJkYy0wZDVkZDA2YWUzODYiLCJjb2duaXRvOmdyb3VwcyI6WyJ1cy1lYXN0LTFfQUd5ME8xRHFvX0ludGVsaUFwcEdyeW1hdHRlckF1dGgwIl0sInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXV0aF90aW1lIjoxNTUwNzYyMDA0LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9BR3kwTzFEcW8iLCJleHAiOjE1NTA3NjU2MDQsImlhdCI6MTU1MDc2MjAwNCwidmVyc2lvbiI6MiwianRpIjoiZjgzODk2NDctMjNjOC00YTJjLTk4OWItMDVjZDUwNmRiYjg4IiwiY2xpZW50X2lkIjoiM2FqOG1qMGptZDk5MHU1M2ViaTU3Y3Q4bjgiLCJ1c2VybmFtZSI6IkludGVsaUFwcEdyeW1hdHRlckF1dGgwX2F1dGgwfDViYzczOWZkYzA3YTM1N2FlN2VjNGUzNCJ9.a6ZXpRVq1t8xQHNhgJc1tXPMXQwljJSo9nylGa-f8hbPuo2ake0tXm6bfwG1fjzzIz2nYxZAznW4C5-YanGSUR87YcwyuMXb-XwK0VnS1RJHf5pNnXnJJx70S5KLJ7ScrBHyDPqXsHZmDtxV9oGar-VBBsoHqoJ0Kn1nQI0Pn7VIsHd_iaTgDOoufQFhXKklCYZZoDc_i8homkjnnuMkUAB16sYvytlgXldjeNGhqQn_mE-BDlQgiT9hOy1leyHF5IIOvYOSTEGO6Yrmkk-XcZlo0J6pvXc82ONPFq4fjt41kmsaB2MPEDwx8DXNZqi23I-pFX7OUm7ZU1Uh55d0mg&id_token=eyJraWQiOiJ1RTVxbVwvdk5PemtyWjFKWFBYSXkzY3hwaE00M25rNjBvV1Vsb0I3emt0RT0iLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiSVFpam5SZU9rLTFFNlY1d3h6cEt6ZyIsInN1YiI6IjE3NTBjMTczLWVmMGEtNDVlMC05YmRjLTBkNWRkMDZhZTM4NiIsImNvZ25pdG86Z3JvdXBzIjpbInVzLWVhc3QtMV9BR3kwTzFEcW9fSW50ZWxpQXBwR3J5bWF0dGVyQXV0aDAiXSwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9BR3kwTzFEcW8iLCJjb2duaXRvOnVzZXJuYW1lIjoiSW50ZWxpQXBwR3J5bWF0dGVyQXV0aDBfYXV0aDB8NWJjNzM5ZmRjMDdhMzU3YWU3ZWM0ZTM0IiwiYXVkIjoiM2FqOG1qMGptZDk5MHU1M2ViaTU3Y3Q4bjgiLCJpZGVudGl0aWVzIjpbeyJ1c2VySWQiOiJhdXRoMHw1YmM3MzlmZGMwN2EzNTdhZTdlYzRlMzQiLCJwcm92aWRlck5hbWUiOiJJbnRlbGlBcHBHcnltYXR0ZXJBdXRoMCIsInByb3ZpZGVyVHlwZSI6IlNBTUwiLCJpc3N1ZXIiOiJ1cm46aW50ZWxsaWFwcC5hdXRoMC5jb20iLCJwcmltYXJ5IjoidHJ1ZSIsImRhdGVDcmVhdGVkIjoiMTU0MDM0NjEzOTE1NCJ9XSwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE1NTA3NjIwMDQsImV4cCI6MTU1MDc2NTYwNCwiaWF0IjoxNTUwNzYyMDA0LCJlbWFpbCI6InJ5YW5AZ3J5bWF0dGVyLmNvbSJ9.ZZ1k6n9siToc6ZpbZRG6F0EFK5UzJ68RCTYN1LAGGlYiO54rIdZcoGmaGRPdFVLMy0RnBgOsEKxv8-W7e1heoJj3GHJezXpney80GhxVhpFvu2HjXMNJpzrHBefKJMrjX5EjErFIH8ERGhCM87cupf9MYJSAo0jc3Rnf81R0nAsbvNI4uoyKp_USMKldliDPdRINR74PcJnp04e_Jk4gZ-lVi_xIYHdqBG5WtaexD-IvD5hizNMteywyLKTUTAc5nnTLZOtiAQqwveePIWcF6keJxpMo59p8_liQc5gB4y-vog61U-KRraNQguHIAbUh8Nk-ViPxeAtR2p9Ywt5RtA&token_type=Bearer&expires_in=3600]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at scripts.TestValidLogin.validLogin(TestValidLogin.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </failure>
  </testcase> <!-- validLogin -->
</testsuite> <!-- scripts.TestValidLogin -->
